spring:
  config:
    import: classpath:messages/messages.yaml

dynamic:
  tables:
    tasks:
      mapKey: tasks
      idColumn: task_id
      questionIdColumn: question_id
      performedTeamNameColumn: performed_team_name

    teams:
      mapKey: teams
      namePostfix: _teams
      idColumn: team_name
      scoreColumn: score

    players:
      mapKey: players
      namePostfix: _players
      idColumn: tg_user_id
      teamNameColumn: team_name

keyboard:
  newGame:
    annotation: Выбор типа игры
    returnMain: Вернуться в главное меню
    freeMode: Свободный режим
    stationMode: Игра по станциям
    back: Назад

  defaultKb:
    returnKb: вернуть клавиатуру
    toGroup: посетить сообщество

  mainKb:
    newGame: Новая игра
    belongGame: Текущие игры
    questions: Вопросы
  Questions:
    show: смотреть банк вопросов
    add: добавить вопрос

  allQuestions:
    delete: удалить
    edit: редактировать
    show_news: показать обновлённый список вопросов