spring:
  config:
    import: classpath:messages/messages.yaml

dynamic:
  tables:
    tasks:
      mapKey: tasks
      idColumn: task_id
      questionIdColumn: question_id
      performedTeamNameColumn: performed_team_name

    teams:
      mapKey: teams
      namePostfix: _teams
      idColumn: team_name
      scoreColumn: score

    players:
      mapKey: players
      namePostfix: _players
      idColumn: tg_user_id
      teamNameColumn: team_name