spring:
  config:
    import: classpath:messages/messages.yaml

document:
  excel:
    mimeType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  temp:
    file:
      prefix: question
      suffix: .xlsx

telegram:
  bot:
    api:
     prefix: https://api.telegram.org/bot

     method:
       getFile: /getFile?file_id=

  file:
    api:
      prefix: https://api.telegram.org/file/bot

viewer:
  questions:
    page:
      size: 5